#!/bin/bash
# requirements:
#   clang 3.7+
#   objdump, readelf
#   ruby
#   git
#   nodejs 5.0+

# current project:
# git clone https://github.com/a1exwang/alex-cpu-test.git -b master alex-machine-tests

if [ $# -eq 1]; then
  FROM_SCRATCH=1
else
  FROM_SCRATCH=0
fi

# install dependencies
sudo apt-get install clang-3.7
sudo update-alternative --install /usr/bin/clang clang /usr/bin/clang-3.7 1000
sudo apt-get install ruby git npm
# install latest nodejs
sudo npm install -g n
sudo n latest

cd ..

if [ $FROM_SCRATCH -eq 1]; then 
  git clone https://github.com/a1exwang/alex-machine.git -b alex-test alex-machine
  git clone https://github.com/a1exwang/llvm.git -b alex-cpu llvm
  git clone https://github.com/a1exwang/lld.git -b alex-cpu llvm/tools/lld
fi

mkdir -p llvm-build
cd llvm-build
cmake -DCMAKE_BUILD_TYPE=Release ../llvm
make llc -j24
make lld -j24
make llvm-mc -j24
make llvm-objdump -j24
cd ..

cd alex-machine
npm install
cd ..

cd alex-machine-tests
./build -l ../llvm-build/bin

node ../alex-machine/simulator/sim.js -p a.out
